# Generated by Django 5.0.2 on 2024-03-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(blank=True, max_length=25, null=True)),
                ('age', models.PositiveIntegerField(default=50)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=6, null=True)),
                ('image', models.ImageField(default='def.jpg', upload_to='images/')),
                ('address', models.TextField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
